spring.application.name=mobile-app-ws
server.error.include-message=always
server.error.include-binding-errors=always

# Root level (affects everything not overridden below)
logging.level.root=INFO

# Your app's packages - see detailed logs from your own code
logging.level.com.appsdeveloperblog=DEBUG

# Spring framework internals
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web=DEBUG

# See incoming HTTP requests, headers, params
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

# Hibernate / JPA SQL logging (if using JPA)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Embedded Tomcat access logs / internals
logging.level.org.apache.catalina=DEBUG
logging.level.org.apache.tomcat=DEBUG